clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

cache:
  - dist-newstyle
  - "C:\\sr"

platform:
  - x86_64
  - x86

environment:
  global:
    CABOPTS:  --http-transport=plain-http --store-dir=C:\\SR
    CHOCOCMD: ghc --version %GHCVER%
  matrix:
    - GHCVER: 8.6.5
    - GHCVER: 8.4.4
    - GHCVER: 8.2.2
    - GHCVER: 8.0.2
    - GHCVER: 7.10.3.2
    - GHCVER: 7.8.4.1
    - GHCVER: 7.6.3.1
    - GHCVER: 7.4.2
    - GHCVER: 7.2.2
    - GHCVER: 7.0.4
    - GHCVER: head

matrix:
  fast_finish: true
  allow_failures:
    - GHCVER: head
  exclude:
    - platform: x86
      GHCVER: head

for:
  -
    matrix:
      only:
        - platform: x86
    environment:
      global:
        GHCOPTS: --forcex86
  -
    matrix:
      only:
        - GHCVER: head
    environment:
      global:
        GHCOPTS: --pre
        CHOCOCMD: ghc-head

install:
 - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
 - choco install %CHOCOCMD% -y %GHCOPTS% %CHOCOPTS% --ignore-dependencies
 - choco install -y cabal %CHOCOPTS%
 - refreshenv
 # TODO: remove once new cabal package has been published
 - set PATH=C:\\ghc\\ghc-%GHCVER%\\bin;C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%

before_build:
 - cabal --version
 - ghc --version
 - cabal %CABOPTS% new-update
 - IF EXIST configure.ac bash -c "autoreconf -i"

build_script:
 - cabal %CABOPTS% new-build -j all

after_build:
 - cabal %CABOPTS%  new-sdist all
